import 'dotenv/config';
import bcrypt from 'bcryptjs';
import cors from 'cors';
import express from 'express';
import jwt from 'jsonwebtoken';
import mongoose from 'mongoose';
import multer from 'multer';
import { mkdirSync } from 'node:fs';
import { extname, join } from 'node:path';
import process from 'node:process';
import { ApprovedProjectArchive, Document, Group, Project, Review, StudentProfile, SystemConfig, User } from './models/index.js';

const app = express();
const port = Number(process.env.PORT || 3001);
const jwtSecret = process.env.JWT_SECRET || 'development-only-change-me';
const mongoUri = process.env.MONGODB_URI;
const groqModel = process.env.GROQ_MODEL || 'llama-3.3-70b-versatile';
const hasGroqApiKey = Boolean(process.env.GROQ_API_KEY && !process.env.GROQ_API_KEY.includes('your_groq_api_key'));
const defaultAiRules = { prioritizeInterdisciplinaryTeams: true, includeSocialImpactScore: true, allowExternalProblemStatements: false, maxRecommendations: 3 };

app.use(cors());
app.use(express.json({ limit: '1mb' }));
const uploadsDir = join(process.cwd(), 'uploads');
mkdirSync(uploadsDir, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: (_req, _file, done) => done(null, uploadsDir), filename: (_req, file, done) => done(null, `${Date.now()}-${Math.round(Math.random() * 1e9)}${extname(file.originalname)}`) }), limits: { fileSize: 10 * 1024 * 1024, files: 3 }, fileFilter: (_req, file, done) => done(null, /pdf|msword|officedocument|powerpoint/.test(file.mimetype)) });
app.use('/uploads', express.static(uploadsDir));

const publicUser = (user) => ({ id: user._id?.toString() || user.id, name: user.name, email: user.email, role: user.role, department: user.department });
const projectPayload = (project) => ({ title: project.title, problemStatement: project.problemStatement, objective: project.objective, technologies: project.technologies || project.recommendedTechnologies || [], difficulty: project.difficulty || project.difficultyLevel || 'Medium', expectedOutcomes: project.expectedOutcomes || [], timeline: project.timeline || project.estimatedTimeline || '' });
const isGroupLeader = (user, group) => group.leader.toString() === user.id;

function authenticate(req, res, next) {
  const token = req.headers.authorization?.startsWith('Bearer ') ? req.headers.authorization.slice(7) : null;
  if (!token) return res.status(401).json({ error: 'Authentication required. Send a Bearer token.' });
  try { req.user = jwt.verify(token, jwtSecret); return next(); } catch { return res.status(401).json({ error: 'Your session is invalid or expired. Sign in again.' }); }
}
const allowRoles = (...allowed) => (req, res, next) => allowed.includes(req.user.role) ? next() : res.status(403).json({ error: `This action requires one of: ${allowed.join(', ')}.` });
async function studentGroup(userId) { return Group.findOne({ members: userId }); }
async function rules() { const config = await SystemConfig.findOne({ key: 'aiRules' }); return config?.value || defaultAiRules; }
function parseRecommendedProjects(content) {
  const withoutFence = String(content || '').trim()
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim();
  const start = withoutFence.indexOf('[');
  const end = withoutFence.lastIndexOf(']');
  if (start === -1 || end === -1 || end < start) throw new Error('Groq did not return a JSON project array.');
  const projects = JSON.parse(withoutFence.slice(start, end + 1));
  if (!Array.isArray(projects) || projects.length !== 3) throw new Error('Groq did not return exactly three projects.');
  return projects;
}

async function seedDemoData() {
  if (await User.exists({})) return;
  const password = await bcrypt.hash('student123', 12);
  const [student, student2, faculty, ccFaculty, admin] = await User.create([
    { name: 'Saanvi Kulkarni', email: 'student@projectpulse.test', password, role: 'STUDENT', department: 'Computer Science' },
    { name: 'Aarav Rao', email: 'student2@projectpulse.test', password, role: 'STUDENT', department: 'Computer Science' },
    { name: 'Dr. Maya Shah', email: 'faculty@projectpulse.test', password: await bcrypt.hash('faculty123', 12), role: 'FACULTY', department: 'Computer Science' },
    { name: 'Dr. Nikhil Mehta', email: 'ccfaculty@projectpulse.test', password: await bcrypt.hash('ccfaculty123', 12), role: 'CC_FACULTY', department: 'Computer Science' },
    { name: 'System Admin', email: 'admin@projectpulse.test', password: await bcrypt.hash('admin123', 12), role: 'ADMIN', department: 'Administration' },
  ]);
  await StudentProfile.create([{ user: student._id, skills: ['React', 'Python'], techInterests: ['AI', 'Web'], areasOfInterest: ['Smart Cities'] }, { user: student2._id, skills: ['Node.js'], techInterests: ['IoT'], areasOfInterest: ['Social Impact'] }]);
  const group = await Group.create({ name: 'Pixel Pioneers', department: 'Computer Science', leader: student._id, members: [student._id, student2._id], preferredTech: ['React', 'Python'], domain: ['Smart Cities'], difficultyLevel: 'Medium', selectedProject: { title: 'Smart Campus Navigator' }, status: 'LOCKED' });
  await Project.create({ group: group._id, department: group.department, ...projectPayload({ title: 'Smart Campus Navigator', problemStatement: 'Students need accessible, real-time campus navigation.', objective: 'Deliver accessible routes and live crowd insights.', recommendedTechnologies: ['React', 'Python', 'PostgreSQL'], difficultyLevel: 'Medium', expectedOutcomes: ['Accessible routes', 'Live occupancy insights'], estimatedTimeline: '12 weeks' }) });
  await SystemConfig.create({ key: 'aiRules', value: defaultAiRules });
  console.log(`Seeded demo accounts for ${faculty.email}, ${ccFaculty.email}, and ${admin.email}.`);
}

app.get('/api/health', (_req, res) => res.json({ status: 'ok', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected', provider: 'groq' }));
app.post('/api/auth/login', async (req, res, next) => { try { const { email, password, role } = req.body || {}; const user = await User.findOne({ email: String(email || '').toLowerCase() }).select('+password'); if (!user || !(await bcrypt.compare(password || '', user.password))) return res.status(401).json({ error: 'Invalid email or password.' }); if (role && role !== user.role) return res.status(403).json({ error: `This account has the ${user.role} role, not ${role}.` }); const token = jwt.sign({ id: user._id.toString(), role: user.role, department: user.department, name: user.name }, jwtSecret, { expiresIn: '8h' }); return res.json({ token, user: publicUser(user) }); } catch (error) { next(error); } });
app.get('/api/auth/me', authenticate, async (req, res, next) => { try { const user = await User.findById(req.user.id); if (!user) return res.status(404).json({ error: 'User not found.' }); return res.json({ user: publicUser(user) }); } catch (error) { next(error); } });
app.put('/api/student-profile', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { const profile = await StudentProfile.findOneAndUpdate({ user: req.user.id }, { user: req.user.id, skills: req.body?.skills || [], techInterests: req.body?.techInterests || [], areasOfInterest: req.body?.areasOfInterest || [] }, { upsert: true, new: true, runValidators: true }); res.json({ profile }); } catch (error) { next(error); } });

app.post('/api/groups', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { if (await studentGroup(req.user.id)) return res.status(409).json({ error: 'You already belong to a group.' }); const { name, minSize = 1, maxSize = 4, preferredTech = [], domain = [], difficultyLevel = 'Medium' } = req.body || {}; if (!name?.trim()) return res.status(400).json({ error: 'Group name is required.' }); const group = await Group.create({ name, department: req.user.department, leader: req.user.id, members: [req.user.id], minSize, maxSize, preferredTech, domain, difficultyLevel }); res.status(201).json({ group }); } catch (error) { next(error); } });
app.get('/api/groups/me', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { const group = await Group.findOne({ members: req.user.id }).populate('members', 'name email role department').populate('leader', 'name email'); res.json({ group }); } catch (error) { next(error); } });
app.post('/api/groups/:groupId/join', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { const group = await Group.findById(req.params.groupId); if (!group) return res.status(404).json({ error: 'Group not found.' }); if (group.status === 'LOCKED' || group.status === 'SUBMITTED') return res.status(409).json({ error: 'This group is locked.' }); if (await studentGroup(req.user.id)) return res.status(409).json({ error: 'Leave your current group before joining another.' }); if (group.members.length >= group.maxSize) return res.status(409).json({ error: 'This group is already full.' }); group.members.push(req.user.id); await group.save(); res.json({ group }); } catch (error) { next(error); } });
app.post('/api/groups/:groupId/select-project', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { const group = await Group.findById(req.params.groupId); if (!group) return res.status(404).json({ error: 'Group not found.' }); if (!isGroupLeader(req.user, group)) return res.status(403).json({ error: 'Only the group leader can select a project.' }); if (group.status === 'LOCKED' || group.status === 'SUBMITTED') return res.status(409).json({ error: 'Project selection is locked.' }); if (!req.body?.project?.title) return res.status(400).json({ error: 'A project with a title is required.' }); group.selectedProject = req.body.project; group.status = 'PROJECT_SELECTED'; await group.save(); res.json({ group }); } catch (error) { next(error); } });
app.post('/api/groups/:groupId/lock-selection', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { const group = await Group.findById(req.params.groupId); if (!group) return res.status(404).json({ error: 'Group not found.' }); if (!isGroupLeader(req.user, group)) return res.status(403).json({ error: 'Only the group leader can lock selection.' }); if (!group.selectedProject?.title) return res.status(400).json({ error: 'Select a project before locking it.' }); group.status = 'LOCKED'; await group.save(); res.json({ group }); } catch (error) { next(error); } });

app.post('/api/submissions', authenticate, allowRoles('STUDENT'), async (req, res, next) => { try { const group = await studentGroup(req.user.id); if (!group) return res.status(400).json({ error: 'Create or join a group before submitting.' }); if (group.status !== 'LOCKED') return res.status(409).json({ error: 'Lock your project selection before submitting.' }); if (await Project.exists({ group: group._id })) return res.status(409).json({ error: 'This group already has a submitted proposal.' }); const data = projectPayload(req.body?.project || group.selectedProject || {}); if (!data.title || !data.problemStatement || !data.objective) return res.status(400).json({ error: 'Project title, problem statement, and objective are required.' }); const project = await Project.create({ group: group._id, department: group.department, ...data }); group.status = 'SUBMITTED'; await group.save(); res.status(201).json({ submission: project }); } catch (error) { next(error); } });
app.get('/api/submissions', authenticate, async (req, res, next) => { try { const filter = req.user.role === 'ADMIN' ? {} : req.user.role === 'STUDENT' ? { group: (await studentGroup(req.user.id))?._id } : { department: req.user.department }; const submissions = filter.group === undefined && req.user.role === 'STUDENT' ? [] : await Project.find(filter).populate('group', 'name members').populate('approvedBy', 'name email'); res.json({ submissions }); } catch (error) { next(error); } });
app.post('/api/submissions/:projectId/documents', authenticate, allowRoles('STUDENT'), upload.array('documents', 3), async (req, res, next) => { try { const project = await Project.findById(req.params.projectId).populate('group'); if (!project) return res.status(404).json({ error: 'Project not found.' }); if (!project.group.members.some((member) => member.toString() === req.user.id)) return res.status(403).json({ error: 'Only group members can upload documents.' }); if (project.detailsLocked) return res.status(409).json({ error: 'Approved project details are locked.' }); if (!req.files?.length) return res.status(400).json({ error: 'Attach PDF, Word, or PowerPoint files using the documents field.' }); const type = String(req.body?.documentType || 'SUPPORTING_DOCUMENT').toUpperCase(); const documents = await Document.insertMany(req.files.map((file) => ({ title: file.originalname, fileUrl: `/uploads/${file.filename}`, type, uploadedBy: req.user.id, projectId: project._id, mimeType: file.mimetype, size: file.size }))); res.status(201).json({ documents }); } catch (error) { next(error); } });

app.get('/api/reviews', authenticate, allowRoles('FACULTY', 'CC_FACULTY'), async (req, res, next) => { try { const submissions = await Project.find({ department: req.user.department }).populate('group', 'name members').populate('approvedBy', 'name'); res.json({ readOnly: req.user.role === 'CC_FACULTY', submissions }); } catch (error) { next(error); } });
async function reviewProject(req, res, next, decision) { try { const project = await Project.findOne({ _id: req.params.projectId, department: req.user.department }); if (!project) return res.status(404).json({ error: 'Project not found in your department.' }); const comments = req.body?.comment?.trim() || (decision === 'APPROVED' ? 'Project approved.' : ''); if (!comments) return res.status(400).json({ error: 'Revision commentary is required.' }); project.status = decision; project.detailsLocked = decision === 'APPROVED'; project.approvedBy = decision === 'APPROVED' ? req.user.id : null; await project.save(); if (decision === 'APPROVED') { const keywords = [...new Set(`${project.title} ${project.technologies.join(' ')}`.toLowerCase().split(/[^a-z0-9+#.]+/).filter((word) => word.length > 2))]; await ApprovedProjectArchive.findOneAndUpdate({ projectId: project._id }, { title: project.title, keywords, projectId: project._id, approvedAt: new Date() }, { upsert: true, new: true, runValidators: true }); } const review = await Review.create({ projectId: project._id, reviewerId: req.user.id, comments, marks: req.body?.marks, milestone: req.body?.milestone || 'Proposal', decision }); res.json({ submission: project, review }); } catch (error) { next(error); } }
app.patch('/api/reviews/:projectId/approve', authenticate, allowRoles('FACULTY'), (req, res, next) => reviewProject(req, res, next, 'APPROVED'));
app.patch('/api/reviews/:projectId/request-revision', authenticate, allowRoles('FACULTY'), (req, res, next) => reviewProject(req, res, next, 'REVISION_REQUIRED'));
app.get('/api/monitoring/projects', authenticate, allowRoles('CC_FACULTY', 'ADMIN'), async (req, res, next) => { try { const filter = req.user.role === 'ADMIN' ? {} : { department: req.user.department }; const projects = await Project.find(filter).populate('group', 'name').lean(); const ids = projects.map((project) => project._id); const docs = await Document.aggregate([{ $match: { projectId: { $in: ids } } }, { $group: { _id: '$projectId', count: { $sum: 1 } } }]); const counts = Object.fromEntries(docs.map((doc) => [doc._id.toString(), doc.count])); res.json({ projects: projects.map((project) => ({ ...project, documentCount: counts[project._id.toString()] || 0 })) }); } catch (error) { next(error); } });

app.get('/api/admin/analytics', authenticate, allowRoles('ADMIN'), async (_req, res, next) => { try { const [projects, groups, students, departments, workflow, byDepartment] = await Promise.all([Project.countDocuments(), Group.countDocuments(), User.countDocuments({ role: 'STUDENT' }), User.distinct('department', { role: { $ne: 'ADMIN' } }), Project.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }]), Project.aggregate([{ $group: { _id: '$department', count: { $sum: 1 } } }])]); const status = Object.fromEntries(workflow.map((item) => [item._id, item.count])); res.json({ totals: { projects, groups, students, departments: departments.length }, workflow: { pending: status.PENDING || 0, approved: status.APPROVED || 0, revisions: status.REVISION_REQUIRED || 0 }, projectsByDepartment: byDepartment.map((item) => ({ department: item._id, count: item.count })) }); } catch (error) { next(error); } });
app.get('/api/admin/ai-rules', authenticate, allowRoles('ADMIN'), async (_req, res, next) => { try { res.json({ rules: await rules() }); } catch (error) { next(error); } });
app.put('/api/admin/ai-rules', authenticate, allowRoles('ADMIN'), async (req, res, next) => { try { const allowed = ['prioritizeInterdisciplinaryTeams', 'includeSocialImpactScore', 'allowExternalProblemStatements', 'maxRecommendations']; const updates = Object.fromEntries(Object.entries(req.body || {}).filter(([key]) => allowed.includes(key))); if ('maxRecommendations' in updates && (!Number.isInteger(Number(updates.maxRecommendations)) || Number(updates.maxRecommendations) < 1 || Number(updates.maxRecommendations) > 10)) return res.status(400).json({ error: 'maxRecommendations must be between 1 and 10.' }); const config = await SystemConfig.findOneAndUpdate({ key: 'aiRules' }, { value: { ...(await rules()), ...updates, ...(updates.maxRecommendations ? { maxRecommendations: Number(updates.maxRecommendations) } : {}) } }, { upsert: true, new: true }); res.json({ rules: config.value }); } catch (error) { next(error); } });

const systemPrompt = 'You are an AI project recommendation engine for university students. Generate exactly 3 unique, innovative, socially impactful final-year project ideas. Avoid duplicates and near-duplicates of previously approved projects. Respect student preferences. Return only a valid JSON array. Each object must contain title, problemStatement, objective, recommendedTechnologies (array), difficultyLevel (Easy, Medium, or Advanced), expectedOutcomes (array), and estimatedTimeline.';
app.post('/api/recommendations', async (req, res, next) => { try { const required = ['groupSize', 'preferredTech', 'difficultyLevel', 'projectDomain', 'previouslyApprovedProjects']; const missing = required.find((field) => req.body?.[field] === undefined || req.body?.[field] === null); if (missing) return res.status(400).json({ error: `Missing required field: ${missing}` }); if (!hasGroqApiKey) return res.status(503).json({ error: 'Groq API key is missing. Add GROQ_API_KEY to .env and restart the server.' }); const archived = await ApprovedProjectArchive.find().select('title keywords -_id').lean(); const blacklist = [...req.body.previouslyApprovedProjects, ...archived.map((item) => `${item.title} ${item.keywords.join(' ')}`)]; const prompt = `${systemPrompt}\n\nAI rules: ${JSON.stringify(await rules())}\nStudent preferences: ${JSON.stringify({ ...req.body, previouslyApprovedProjects: blacklist })}`; const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.GROQ_API_KEY.trim()}` }, body: JSON.stringify({ model: groqModel, messages: [{ role: 'system', content: systemPrompt }, { role: 'user', content: prompt }], temperature: 0.8 }) }); if (!response.ok) return res.status(502).json({ error: `Groq request failed with status ${response.status}.` }); const content = (await response.json())?.choices?.[0]?.message?.content; res.json({ projects: parseRecommendedProjects(content) }); } catch (error) { next(error); } });

app.use((error, _req, res, _next) => { console.error(error); if (error instanceof multer.MulterError) return res.status(400).json({ error: error.message }); if (error?.name === 'ValidationError') return res.status(400).json({ error: error.message }); return res.status(500).json({ error: 'The server could not process this request.' }); });

if (!mongoUri) { console.error('MONGODB_URI is missing. Add it to .env before starting the server.'); process.exit(1); }
mongoose.connect(mongoUri).then(seedDemoData).then(() => app.listen(port, () => console.log(`ProjectPulse API listening on http://localhost:${port}`))).catch((error) => { console.error('MongoDB connection failed:', error.message); process.exit(1); });
